name: CoSim

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:

  CoSim:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: docker://ghdl/vunit:llvm
      with:
        args: cosim/dpi-ffi/ghdl-vffi/test/run.py
