name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:


  Compliance:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: ghdl/setup-ghdl-ci@master
        with:
          backend: gcc

      - uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - run: |
          python -m pip install -r requirements.txt
          python run.py -k -v -p10


  CoSim:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: docker://ghdl/vunit:llvm
        with:
          args: cosim/dpi-ffi/ghdl-vffi/test/run.py


  Doc:
    runs-on: ubuntu-latest
    name: '📓 Doc'
    steps:

    - name: 🧰 Checkout
      uses: actions/checkout@v3

    - name: 📓 BuildTheDocs (BTD)
      uses: buildthedocs/btd@v0
      with:
        token: ${{ github.token }}
        skip-deploy: ${{ github.event_name == 'pull_request' }}

    - name: '📤 Upload artifact: Sphinx HTML'
      uses: actions/upload-artifact@v3
      with:
        name: Documentation-HTML
        path: doc/_build/html
