name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [ Test ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: docker://ghdl/vunit:llvm
      with:
        args: python3 run.py

    - uses: docker://ghdl/vunit:llvm
      with:
        args: ./cosim/dpi-ffi/test/run.sh
