name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:

  Compliance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ghdl/setup-ghdl-ci@master
      with:
        backend: gcc
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - run: |
        python -m pip install -r requirements.txt
        python run.py -v -p10
