name: 'test'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - run: docker run --rm -tv $(pwd):/src -w /src ghdl/vunit:llvm python3 run.py

#    - uses: actions/upload-artifact@master
#      with:
#        name: <name of the resulting zipfile
#        path: <directory to zip and upload>
