name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:


  Compliance:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tool:
          - ghdl
          - ghdl/llvm
          - nvc

    steps:

      - uses: actions/checkout@v3

      # Cannot use 'docker://' syntax here because using variables (e.g matrix.tool) is not supported.
      # See https://github.com/orgs/community/discussions/9049.
      # Therefore, we need to call docker explicitly.
      - run: >-
          docker run --rm -t
          -v $(pwd):/wrk -w /wrk
          -v $GITHUB_STEP_SUMMARY:/wrk/GHSS
          -e GITHUB_STEP_SUMMARY=/wrk/GHSS
          -e GITHUB_ACTIONS
          gcr.io/hdl-containers/${{ matrix.tool }}
          ./.github/run.sh


  CoSim:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: docker://ghdl/vunit:llvm
        with:
          args: cosim/dpi-ffi/ghdl-vffi/test/run.py


  Doc:
    runs-on: ubuntu-latest
    name: '📓 Doc'
    steps:

    - name: 🧰 Checkout
      uses: actions/checkout@v3

    - name: 📓 BuildTheDocs (BTD)
      uses: buildthedocs/btd@v0
      with:
        token: ${{ github.token }}
        skip-deploy: ${{ github.event_name == 'pull_request' }}

    - name: '📤 Upload artifact: Sphinx HTML'
      uses: actions/upload-artifact@v3
      with:
        name: Documentation-HTML
        path: doc/_build/html
